/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 15
#define SYMBOL_COUNT 21
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_PIPE = 5,
  sym_inlinestr = 6,
  sym_float = 7,
  sym_number = 8,
  sym_string = 9,
  sym_dot_method = 10,
  sym_named_ref = 11,
  sym_symbol = 12,
  sym_comment = 13,
  sym_source_file = 14,
  sym__expr = 15,
  sym_sexpr = 16,
  sym_qexpr = 17,
  sym_qexpr_item = 18,
  aux_sym_source_file_repeat1 = 19,
  aux_sym_qexpr_repeat1 = 20,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PIPE] = "|",
  [sym_inlinestr] = "inlinestr",
  [sym_float] = "float",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_dot_method] = "dot_method",
  [sym_named_ref] = "named_ref",
  [sym_symbol] = "symbol",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__expr] = "_expr",
  [sym_sexpr] = "sexpr",
  [sym_qexpr] = "qexpr",
  [sym_qexpr_item] = "qexpr_item",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_qexpr_repeat1] = "qexpr_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_inlinestr] = sym_inlinestr,
  [sym_float] = sym_float,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_dot_method] = sym_dot_method,
  [sym_named_ref] = sym_named_ref,
  [sym_symbol] = sym_symbol,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__expr] = sym__expr,
  [sym_sexpr] = sym_sexpr,
  [sym_qexpr] = sym_qexpr,
  [sym_qexpr_item] = sym_qexpr_item,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_qexpr_repeat1] = aux_sym_qexpr_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_inlinestr] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_dot_method] = {
    .visible = true,
    .named = true,
  },
  [sym_named_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_sexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_qexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_qexpr_item] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_qexpr_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static const TSCharacterRange sym_symbol_character_set_1[] = {
  {'!', '!'}, {'$', '&'}, {'*', '+'}, {'-', ':'}, {'<', '?'}, {'A', 'Z'}, {'\\', '\\'}, {'_', '_'},
  {'a', 'z'}, {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '"', 1,
        '(', 5,
        ')', 6,
        '-', 19,
        '.', 21,
        ';', 25,
        '@', 2,
        '{', 7,
        '|', 9,
        '}', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('/' <= lookahead && lookahead <= 'Z') ||
          lookahead == '\\' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '~')) ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(16);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_inlinestr);
      if (lookahead == '\r') ADVANCE(12);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_inlinestr);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '}') ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_inlinestr);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '}') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_dot_method);
      if ((set_contains(sym_symbol_character_set_1, 10, lookahead)) &&
          (lookahead < '0' || '9' < lookahead) &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          lookahead != '_' &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_named_ref);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '.') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (set_contains(sym_symbol_character_set_1, 10, lookahead)) ADVANCE(24);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (set_contains(sym_symbol_character_set_1, 10, lookahead)) ADVANCE(24);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('-' <= lookahead && lookahead <= ':') ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '\\' ||
          lookahead == '~') ADVANCE(24);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (set_contains(sym_symbol_character_set_1, 10, lookahead)) ADVANCE(24);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (set_contains(sym_symbol_character_set_1, 10, lookahead)) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_symbol);
      if (set_contains(sym_symbol_character_set_1, 10, lookahead)) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(25);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 11},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_dot_method] = ACTIONS(1),
    [sym_named_ref] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym__expr] = STATE(7),
    [sym_sexpr] = STATE(7),
    [sym_qexpr] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [sym_string] = ACTIONS(11),
    [sym_dot_method] = ACTIONS(13),
    [sym_named_ref] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__expr] = STATE(13),
    [sym_sexpr] = STATE(13),
    [sym_qexpr] = STATE(13),
    [sym_qexpr_item] = STATE(3),
    [aux_sym_qexpr_repeat1] = STATE(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(17),
    [sym_float] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(19),
    [sym_dot_method] = ACTIONS(21),
    [sym_named_ref] = ACTIONS(19),
    [sym_symbol] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__expr] = STATE(13),
    [sym_sexpr] = STATE(13),
    [sym_qexpr] = STATE(13),
    [sym_qexpr_item] = STATE(4),
    [aux_sym_qexpr_repeat1] = STATE(4),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_PIPE] = ACTIONS(17),
    [sym_float] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(19),
    [sym_dot_method] = ACTIONS(21),
    [sym_named_ref] = ACTIONS(19),
    [sym_symbol] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__expr] = STATE(13),
    [sym_sexpr] = STATE(13),
    [sym_qexpr] = STATE(13),
    [sym_qexpr_item] = STATE(4),
    [aux_sym_qexpr_repeat1] = STATE(4),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(28),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_PIPE] = ACTIONS(33),
    [sym_float] = ACTIONS(36),
    [sym_number] = ACTIONS(39),
    [sym_string] = ACTIONS(36),
    [sym_dot_method] = ACTIONS(39),
    [sym_named_ref] = ACTIONS(36),
    [sym_symbol] = ACTIONS(39),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__expr] = STATE(5),
    [sym_sexpr] = STATE(5),
    [sym_qexpr] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(42),
    [anon_sym_LPAREN] = ACTIONS(44),
    [anon_sym_RPAREN] = ACTIONS(42),
    [anon_sym_LBRACE] = ACTIONS(47),
    [sym_float] = ACTIONS(50),
    [sym_number] = ACTIONS(53),
    [sym_string] = ACTIONS(50),
    [sym_dot_method] = ACTIONS(53),
    [sym_named_ref] = ACTIONS(50),
    [sym_symbol] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__expr] = STATE(8),
    [sym_sexpr] = STATE(8),
    [sym_qexpr] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(56),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_float] = ACTIONS(58),
    [sym_number] = ACTIONS(60),
    [sym_string] = ACTIONS(58),
    [sym_dot_method] = ACTIONS(60),
    [sym_named_ref] = ACTIONS(58),
    [sym_symbol] = ACTIONS(60),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym__expr] = STATE(5),
    [sym_sexpr] = STATE(5),
    [sym_qexpr] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(62),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_float] = ACTIONS(64),
    [sym_number] = ACTIONS(66),
    [sym_string] = ACTIONS(64),
    [sym_dot_method] = ACTIONS(66),
    [sym_named_ref] = ACTIONS(64),
    [sym_symbol] = ACTIONS(66),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym__expr] = STATE(5),
    [sym_sexpr] = STATE(5),
    [sym_qexpr] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(68),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_float] = ACTIONS(64),
    [sym_number] = ACTIONS(66),
    [sym_string] = ACTIONS(64),
    [sym_dot_method] = ACTIONS(66),
    [sym_named_ref] = ACTIONS(64),
    [sym_symbol] = ACTIONS(66),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(70),
    [anon_sym_LPAREN] = ACTIONS(70),
    [anon_sym_RPAREN] = ACTIONS(70),
    [anon_sym_LBRACE] = ACTIONS(70),
    [anon_sym_RBRACE] = ACTIONS(70),
    [anon_sym_PIPE] = ACTIONS(70),
    [sym_float] = ACTIONS(70),
    [sym_number] = ACTIONS(72),
    [sym_string] = ACTIONS(70),
    [sym_dot_method] = ACTIONS(72),
    [sym_named_ref] = ACTIONS(70),
    [sym_symbol] = ACTIONS(72),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(74),
    [anon_sym_LPAREN] = ACTIONS(74),
    [anon_sym_RPAREN] = ACTIONS(74),
    [anon_sym_LBRACE] = ACTIONS(74),
    [anon_sym_RBRACE] = ACTIONS(74),
    [anon_sym_PIPE] = ACTIONS(74),
    [sym_float] = ACTIONS(74),
    [sym_number] = ACTIONS(76),
    [sym_string] = ACTIONS(74),
    [sym_dot_method] = ACTIONS(76),
    [sym_named_ref] = ACTIONS(74),
    [sym_symbol] = ACTIONS(76),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(78),
    [anon_sym_LPAREN] = ACTIONS(78),
    [anon_sym_RPAREN] = ACTIONS(78),
    [anon_sym_LBRACE] = ACTIONS(78),
    [anon_sym_RBRACE] = ACTIONS(78),
    [anon_sym_PIPE] = ACTIONS(78),
    [sym_float] = ACTIONS(78),
    [sym_number] = ACTIONS(80),
    [sym_string] = ACTIONS(78),
    [sym_dot_method] = ACTIONS(80),
    [sym_named_ref] = ACTIONS(78),
    [sym_symbol] = ACTIONS(80),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(82),
    [anon_sym_LPAREN] = ACTIONS(82),
    [anon_sym_RPAREN] = ACTIONS(82),
    [anon_sym_LBRACE] = ACTIONS(82),
    [anon_sym_RBRACE] = ACTIONS(82),
    [anon_sym_PIPE] = ACTIONS(82),
    [sym_float] = ACTIONS(82),
    [sym_number] = ACTIONS(84),
    [sym_string] = ACTIONS(82),
    [sym_dot_method] = ACTIONS(84),
    [sym_named_ref] = ACTIONS(82),
    [sym_symbol] = ACTIONS(84),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [anon_sym_LPAREN] = ACTIONS(86),
    [anon_sym_LBRACE] = ACTIONS(86),
    [anon_sym_RBRACE] = ACTIONS(86),
    [anon_sym_PIPE] = ACTIONS(86),
    [sym_float] = ACTIONS(86),
    [sym_number] = ACTIONS(88),
    [sym_string] = ACTIONS(86),
    [sym_dot_method] = ACTIONS(88),
    [sym_named_ref] = ACTIONS(86),
    [sym_symbol] = ACTIONS(88),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(14)] = {
    [anon_sym_LPAREN] = ACTIONS(90),
    [anon_sym_LBRACE] = ACTIONS(90),
    [anon_sym_RBRACE] = ACTIONS(90),
    [anon_sym_PIPE] = ACTIONS(90),
    [sym_float] = ACTIONS(90),
    [sym_number] = ACTIONS(92),
    [sym_string] = ACTIONS(90),
    [sym_dot_method] = ACTIONS(92),
    [sym_named_ref] = ACTIONS(90),
    [sym_symbol] = ACTIONS(92),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
  [7] = 2,
    ACTIONS(96), 1,
      sym_inlinestr,
    ACTIONS(98), 1,
      sym_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(15)] = 0,
  [SMALL_STATE(16)] = 7,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qexpr_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qexpr_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_qexpr_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qexpr_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qexpr_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_qexpr_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexpr, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexpr, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qexpr, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qexpr, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sexpr, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sexpr, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qexpr, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qexpr, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qexpr_item, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qexpr_item, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qexpr_item, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qexpr_item, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rooture(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
